apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    vamp-managed: enabled
    cluster: default
    project: default
  name: vamp-demo
spec:
  finalizers:
  - kubernetes
status:
  phase: Active