apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    vamp-managed: enabled
    cluster: default
    project: default
  name: vamp-test1
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app1
  name: vamp-test-deployment1
  namespace: vamp-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      deployment: deployment1
  template:
    metadata:
      labels:
        app: app1
        deployment: deployment1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: app1-deployment1
        image: magneticio/nodewebservice:2.0.13
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        name: deployment1-0
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app1
  name: vamp-test-deployment2
  namespace: vamp-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      deployment: deployment2
  template:
    metadata:
      labels:
        app: app1
        deployment: deployment2
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: app1-deployment2
        image: magneticio/nodewebservice:2.0.13
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        name: deployment2-0
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app1
  name: vamp-test-deployment3
  namespace: vamp-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      deployment: deployment3
  template:
    metadata:
      labels:
        app: app1
        deployment: deployment3
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: app1-deployment3
        image: magneticio/nodewebservice:2.0.13
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        name: deployment3-0
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    vamp-managed: enabled
    cluster: default
    project: default
  name: vamp-test2
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app2
  name: vamp-test-deployment1
  namespace: vamp-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      deployment: deployment1
  template:
    metadata:
      labels:
        app: app2
        deployment: deployment1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: app2-deployment1
        image: magneticio/nodewebservice:2.0.13
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        name: deployment1-0
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app2
  name: vamp-test-deployment2
  namespace: vamp-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      deployment: deployment2
  template:
    metadata:
      labels:
        app: app2
        deployment: deployment2
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: app2-deployment2
        image: magneticio/nodewebservice:2.0.13
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        name: deployment2-0
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app2
  name: vamp-test-deployment3
  namespace: vamp-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      deployment: deployment3
  template:
    metadata:
      labels:
        app: app2
        deployment: deployment3
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: app2-deployment3
        image: magneticio/nodewebservice:2.0.13
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        name: deployment3-0
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    vamp-managed: enabled
    cluster: default
    project: default
  name: vamp-test3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app4
  name: vamp-test-deployment1
  namespace: vamp-test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
      deployment: deployment1
  template:
    metadata:
      labels:
        app: app4
        deployment: deployment1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: app4-deployment1
        image: magneticio/nodewebservice:2.0.13
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        name: deployment1-0
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
