kind: Service
apiVersion: v1
metadata:
 name: vamp-hazelcast
 namespace: vamp-system
spec:
 selector:
   app: vamp
 ports:
 - protocol: TCP
   port: 5701
   targetPort: 5701
---
apiVersion: v1
kind: Secret
metadata:
  name: vamprootpassword
  namespace: vamp-system
type: Opaque
data:
  password: VAMP_ROOT_PASSWORD
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vamp
    deployment: vamp
  name: vamp
  namespace: vamp-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vamp
      deployment: vamp
  template:
    metadata:
      labels:
        app: vamp
        deployment: vamp
    spec:
      containers:
      - env:
        - name: MODE
          value: VAMP_MODE
        - name: DBURL
          value: VAMP_DB_URL
        - name: DBNAME
          value: VAMP_DB_NAME
        - name: ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
                name: vamprootpassword
                key: password
        image: VAMP_VERSION
        imagePullPolicy: IfNotPresent
        name: vamp
        ports:
        - containerPort: 8888
          protocol: TCP
        - containerPort: 5701
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: vamp2imagepull
---
kind: Service
apiVersion: v1
metadata:
 name: vamp
 namespace: vamp-system
spec:
 selector:
   app: vamp
 ports:
 - protocol: TCP
   port: 8888
   targetPort: 8888
 type: LoadBalancer
