kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vamp-sa-cluster-admin-binding
subjects:
- kind: User
  name: system:serviceaccount:vamp-system:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: vamp2imagepull
  namespace: vamp-system
type: kubernetes.io/dockercfg
data:
   .dockercfg: eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImRtRnRjREp3ZFd4c09uWmhiWEF5Y0hWc2JFWnNkWGc9In19
---
kind: Service
apiVersion: v1
metadata:
 name: vamp-hazelcast
 namespace: vamp-system
spec:
 selector:
   app: vamp
 ports:
 - protocol: TCP
   port: 5701
   targetPort: 5701
---
apiVersion: v1
kind: Secret
metadata:
  name: vamprootpassword
  namespace: vamp-system
type: Opaque
data:
  password: VAMP_ROOT_PASSWORD
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vamp
    deployment: vamp
  name: vamp
  namespace: vamp-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vamp
      deployment: vamp
  template:
    metadata:
      labels:
        app: vamp
        deployment: vamp
    spec:
      containers:
      - env:
        - name: MODE
          value: "IN_CLUSTER"
        - name: DBURL
          value: VAMP_DB_URL
        - name: DBNAME
          value: VAMP_DB_NAME
        - name: ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
                name: vamprootpassword
                key: password
        image: magneticio/vamp2:0.5.8-valce-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: vamp
        ports:
        - containerPort: 8888
          protocol: TCP
        - containerPort: 5701
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: vamp2imagepull
---
kind: Service
apiVersion: v1
metadata:
 name: vamp
 namespace: vamp-system
spec:
 selector:
   app: vamp
 ports:
 - protocol: TCP
   port: 8888
   targetPort: 8888
 type: LoadBalancer
