apiVersion: v1
kind: Namespace
metadata:
  name: vamp-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vamp-sa-cluster-admin-binding
subjects:
- kind: User
  name: system:serviceaccount:vamp-system:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: vamp2imagepull
  namespace: vamp-system
type: kubernetes.io/dockercfg
data:
   .dockercfg: eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImRtRnRjREp3ZFd4c09uWmhiWEF5Y0hWc2JFWnNkWGc9In19